import { useEffect, useState } from 'react'
import {
  AlertOctagon,
  Building,
  CheckCircle2,
  Clock,
  Download,
  FileCheck,
  FileText,
  Printer,
  Shield,
  Truck,
  Users,
} from 'lucide-react'
import { useAeris } from '@/services/dataContext'
import './ActionsWorkbenchView.css'

const STORAGE_KEY = 'aeris_action_checklist'

export default function ActionsWorkbenchView() {
  const { actions, rankedSites } = useAeris()
  const [checkedMap, setCheckedMap] = useState<Record<string, boolean>>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY)
      return saved ? JSON.parse(saved) : {}
    } catch {
      return {}
    }
  })
  const [activeFilter, setActiveFilter] = useState<'all' | 'schools' | 'hospitals' | 'authorities'>('all')

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(checkedMap))
    } catch {
      // ignore
    }
  }, [checkedMap])

  const siteActions = actions?.actions ?? []
  const authorityActions = actions?.authority_actions ?? []
  const summary = actions?.summary ?? ''

  const toggleCheck = (id: string) => {
    setCheckedMap((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  const handleMarkAll = () => {
    const next: Record<string, boolean> = { ...checkedMap }
    siteActions.forEach((a, i) => { next[`site_${i}`] = true })
    authorityActions.forEach((_, i) => { next[`auth_${i}`] = true })
    setCheckedMap(next)
  }

  const handleReset = () => {
    setCheckedMap({})
  }

  // Calculate readiness
  const totalTasks = siteActions.length + authorityActions.length
  const completedTasks = Object.values(checkedMap).filter(Boolean).length
  const completionPct = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0

  // Export CSV
  const exportDirectivesCsv = () => {
    const headers = ['Directive ID', 'Target Authority / Site', 'Mandatory Action', 'Scientific Rationale', 'Statutory Deadline', 'Dispatch Status']
    const rows = [
      ...authorityActions.map((a, i) => [
        `AUTH-${i + 1}`,
        `"${a.who.replace(/"/g, '""')}"`,
        `"${a.action.replace(/"/g, '""')}"`,
        `"${a.reason.replace(/"/g, '""')}"`,
        'Immediate (0-2h)',
        checkedMap[`auth_${i}`] ? 'DISPATCHED' : 'PENDING',
      ]),
      ...siteActions.map((s, i) => [
        `SITE-${s.site_id}`,
        `"${s.who.replace(/"/g, '""')}"`,
        `"${s.action.replace(/"/g, '""')}"`,
        `"${s.reason.replace(/"/g, '""')}"`,
        `${s.deadline_hours}h ETA`,
        checkedMap[`site_${i}`] ? 'DISPATCHED' : 'PENDING',
      ]),
    ]

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n')
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `AERIS_CPCB_Directives_${new Date().toISOString().slice(0, 10)}.csv`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="actions-workbench-view">
      {/* Header */}
      <div className="view-header">
        <div className="view-title-group">
          <div className="view-badge">
            <Shield size={14} />
            <span>CAQM / CPCB Statutory Enforcement Hub</span>
          </div>
          <h1 className="view-title">Protective Actions &amp; Directive Operations Command</h1>
          <p className="view-subtitle">
            Binding public health, transportation diversion, and institutional mitigation directives generated by AERIS multi-agent reasoning.
          </p>
        </div>

        <div className="view-actions">
          <button className="btn-secondary" onClick={() => window.print()}>
            <Printer size={15} />
            <span>Print Executive Brief</span>
          </button>
          <button className="btn-primary" onClick={exportDirectivesCsv}>
            <Download size={15} />
            <span>Export Directives CSV</span>
          </button>
        </div>
      </div>

      {/* Emergency Status Banner */}
      <div className="grap-banner">
        <div className="grap-left">
          <div className="grap-icon">
            <AlertOctagon size={24} />
          </div>
          <div className="grap-text">
            <span className="grap-level">GRAP STAGE IV (SEVERE+ PROTOCOL) ENFORCED</span>
            <span className="grap-desc">
              Commission for Air Quality Management (CAQM) Order No. 44/2026: Mandatory 8-point emergency intervention protocol active across NCR.
            </span>
          </div>
        </div>

        <div className="grap-progress-box">
          <div className="progress-labels">
            <span>Readiness Gauge:</span>
            <strong>{completedTasks} of {totalTasks} Dispatched ({completionPct}%)</strong>
          </div>
          <div className="progress-track">
            <div className="progress-fill" style={{ width: `${completionPct}%` }} />
          </div>
        </div>
      </div>

      {/* Inter-Agency Regulatory Directives Grid */}
      <div className="authorities-section">
        <div className="section-header">
          <div className="sec-title-group">
            <Truck size={18} />
            <h2>Inter-Agency Authority Directives (State &amp; Municipal)</h2>
          </div>
          <div className="sec-actions">
            <button className="btn-text" onClick={handleMarkAll}>Mark All Dispatched</button>
            <button className="btn-text" onClick={handleReset}>Reset</button>
          </div>
        </div>

        <div className="authorities-grid">
          {authorityActions.map((auth, idx) => {
            const isDone = checkedMap[`auth_${idx}`]
            return (
              <div
                key={idx}
                className={`auth-card ${isDone ? 'done' : ''}`}
                onClick={() => toggleCheck(`auth_${idx}`)}
              >
                <div className="auth-card-top">
                  <span className="auth-who">{auth.who}</span>
                  <input
                    type="checkbox"
                    checked={!!isDone}
                    onChange={() => {}}
                    className="auth-checkbox"
                  />
                </div>
                <div className="auth-action-text">{auth.action}</div>
                <div className="auth-reason">{auth.reason}</div>
                <div className="auth-card-footer">
                  <span className="deadline-badge">
                    <Clock size={12} /> Statutory: Immediate
                  </span>
                  <span className={`status-pill ${isDone ? 'dispatched' : 'pending'}`}>
                    {isDone ? '✓ Dispatched' : 'Pending Order'}
                  </span>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Facility-Level Directives */}
      <div className="facilities-section">
        <div className="section-header">
          <div className="sec-title-group">
            <Building size={18} />
            <h2>Targeted Facility-Level Operational Orders</h2>
          </div>
        </div>

        <div className="facility-directives-list">
          {siteActions.map((siteAct, idx) => {
            const isDone = checkedMap[`site_${idx}`]
            return (
              <div
                key={siteAct.site_id}
                className={`fac-directive-row ${isDone ? 'done' : ''}`}
                onClick={() => toggleCheck(`site_${idx}`)}
              >
                <div className="fac-check-col">
                  <input
                    type="checkbox"
                    checked={!!isDone}
                    onChange={() => {}}
                    className="auth-checkbox"
                  />
                  <span className="fac-priority">Priority #{siteAct.priority}</span>
                </div>

                <div className="fac-main-col">
                  <div className="fac-who-row">
                    <strong>{siteAct.who}</strong>
                    <span className="fac-eta-badge">
                      <Clock size={12} /> Plume ETA: {siteAct.deadline_hours}h deadline
                    </span>
                  </div>
                  <div className="fac-action-stmt">{siteAct.action}</div>
                  <div className="fac-reason-stmt">{siteAct.reason}</div>
                </div>

                <div className="fac-status-col">
                  <span className={`status-pill ${isDone ? 'dispatched' : 'pending'}`}>
                    {isDone ? '✓ Executed' : 'Awaiting Confirmation'}
                  </span>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Agent Reasoning Brief */}
      {summary && (
        <div className="agent-brief-panel">
          <div className="brief-header">
            <FileText size={16} />
            <h3>Autonomous Agent Reasoning Audit Log</h3>
          </div>
          <div className="brief-content">{summary}</div>
        </div>
      )}
    </div>
  )
}
