import { useState } from 'react'
import { X, Download, ShieldCheck, AlertCircle, Building2, School, Clock, CheckCircle2 } from 'lucide-react'
import { useAeris } from '@/services/dataContext'
import './ActionsModal.css'

export default function ActionsModal() {
  const { actions, showActionsModal, setShowActionsModal } = useAeris()
  const [activeTab, setActiveTab] = useState<'sites' | 'authority'>('sites')
  const [dispatched, setDispatched] = useState<Record<string, boolean>>({})

  if (!showActionsModal || !actions) return null

  const handleDispatch = (id: string) => {
    setDispatched(prev => ({ ...prev, [id]: true }))
  }

  const exportAdvisory = () => {
    const lines = [
      '========================================================================',
      '               AERIS AI EMERGENCY AIR QUALITY ADVISORY',
      '========================================================================',
      `Issued: ${actions.generated_at}`,
      '',
      'EXECUTIVE SUMMARY:',
      actions.summary,
      '',
      '------------------------------------------------------------------------',
      'SITE-SPECIFIC PREVENTIVE DIRECTIVES:',
      '------------------------------------------------------------------------',
      ...actions.actions.map(
        a => `[Priority #${a.priority}] To: ${a.who}\nAction: ${a.action}\nDeadline: In ${a.deadline_hours}h | Reason: ${a.reason}\n`
      ),
      '------------------------------------------------------------------------',
      'REGULATORY & AUTHORITY DIRECTIVES:',
      '------------------------------------------------------------------------',
      ...actions.authority_actions.map(
        a => `Authority: ${a.who}\nMandate: ${a.action}\nReason: ${a.reason}\n`
      ),
      '========================================================================',
    ]

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `AERIS_Advisory_${new Date().toISOString().slice(0, 10)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="modal-backdrop" onClick={() => setShowActionsModal(false)}>
      <div className="modal-container card" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="modal-header">
          <div className="modal-header-left">
            <div className="modal-icon-badge">
              <ShieldCheck size={20} color="#22734F" />
            </div>
            <div>
              <div className="modal-title-row">
                <h2 className="modal-title">AERIS Action Directives</h2>
                <span className="badge-active">Verified Live Data</span>
              </div>
              <p className="modal-subtitle">Prioritized interventions generated by the AERIS Strands Agent</p>
            </div>
          </div>
          <button
            className="icon-btn modal-close-btn"
            onClick={() => setShowActionsModal(false)}
            aria-label="Close modal"
          >
            <X size={18} />
          </button>
        </div>

        {/* Executive Summary */}
        <div className="modal-summary-banner">
          <AlertCircle size={18} className="summary-banner-icon" />
          <div className="summary-banner-text">{actions.summary}</div>
        </div>

        {/* Navigation Tabs */}
        <div className="modal-tabs">
          <button
            className={`modal-tab ${activeTab === 'sites' ? 'active' : ''}`}
            onClick={() => setActiveTab('sites')}
          >
            Institutional Actions ({actions.actions.length})
          </button>
          <button
            className={`modal-tab ${activeTab === 'authority' ? 'active' : ''}`}
            onClick={() => setActiveTab('authority')}
          >
            Regulatory Directives ({actions.authority_actions.length})
          </button>
        </div>

        {/* Tab Content */}
        <div className="modal-body">
          {activeTab === 'sites' ? (
            <div className="actions-card-list">
              {actions.actions.map(item => {
                const isDispatched = !!dispatched[item.site_id]
                const isHospital = item.who.toLowerCase().includes('hospital') || item.who.toLowerCase().includes('medical')
                return (
                  <div key={item.site_id} className="action-detail-card">
                    <div className="action-card-top">
                      <div className="action-target-info">
                        <span className="action-priority-tag">#{item.priority} Priority</span>
                        <div className="action-facility-icon">
                          {isHospital ? <Building2 size={16} /> : <School size={16} />}
                        </div>
                        <span className="action-who">{item.who}</span>
                      </div>
                      <div className="action-deadline">
                        <Clock size={13} />
                        <span>Deploy within {item.deadline_hours}h</span>
                      </div>
                    </div>

                    <div className="action-instruction">{item.action}</div>

                    <div className="action-footer">
                      <div className="action-reason">
                        <strong>Evidence:</strong> {item.reason}
                      </div>
                      <button
                        className={`dispatch-btn ${isDispatched ? 'dispatched' : ''}`}
                        onClick={() => handleDispatch(item.site_id)}
                      >
                        {isDispatched ? (
                          <>
                            <CheckCircle2 size={13} /> Dispatched
                          </>
                        ) : (
                          'Dispatch Alert'
                        )}
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            <div className="actions-card-list">
              {actions.authority_actions.map((item, idx) => (
                <div key={idx} className="action-detail-card authority-card">
                  <div className="action-card-top">
                    <span className="authority-name">{item.who}</span>
                    <span className="authority-scope-tag">Regulatory Mandate</span>
                  </div>
                  <div className="action-instruction">{item.action}</div>
                  <div className="action-reason">
                    <strong>Jurisdiction & Trigger:</strong> {item.reason}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="modal-footer">
          <div className="modal-footer-note">
            Directives automatically updated every 15 minutes as new wind & plume vectors arrive.
          </div>
          <div className="modal-footer-actions">
            <button className="btn-secondary" onClick={exportAdvisory}>
              <Download size={14} />
              Export Advisory (TXT)
            </button>
            <button className="btn-primary" onClick={() => setShowActionsModal(false)}>
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
